# Generated by Django 5.2.2 on 2025-06-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='users_profile',
        ),
    ]
